syntax = "proto3";
package proto;

option go_package="./proto";

// import "types/proto/base.proto";

message Service {
    string name = 1;
    string host = 3;
    int32 port = 4;
    string username = 7;
    string password = 8;
    string db = 11;  // for redis/database
}

message Log {
    string path = 1;
    string file = 2;
    string level = 3;
    int32 mage = 4;
    int32 msize = 8;
    int32 mbackup = 9;
    bool localtime = 15;
    bool compress = 16;
    bool console = 17;
    bool error= 18;// enable standalone 'error.log' filters ERROR level logs
}

message Api {
    string name = 1;
    string url = 2;
    string token = 3;
    string secret = 6;
    string key = 7;
}

message Tracer {
    string name = 1;
    string version = 2;
    string protocol = 10;
    string host = 11;
    int32 port = 12;
    bool enabled = 13;
}